#!/usr/bin/env bash
#
# build-custom-bootdisk.sh — build a self-extracting Amix "add-on" floppy image
# that ships extra files (e.g. a hardware driver + an install script) to users.
#
# It mirrors the mechanism of the real Amix 2.1 PATCH disk (see
# docs/boot-disks/anatomy-patch-adf.md): a small /sbin/sh header in the first
# 1 KB, followed by an SVR4 ASCII (newc) cpio archive of your payload. On Amix
# the header script extracts the trailing cpio into the filesystem and runs your
# installer.
#
# WHAT THIS DOES (cross-host, testable):  produces a structurally-correct image.
# WHAT IT DOES NOT DO:  it does NOT regenerate the COMPRESSED, CHECKSUMMED Amix
#   *boot* floppy (boot.adf) — that bootstrap/kernel format is not yet fully
#   reverse-engineered (🔴, see docs/boot-disks/adding-drivers-to-boot-disk.md).
#   Use this for an add-on/driver-install disk, and relink drivers into the
#   on-disk boot partition with `make bootpart` (docs/drivers/kernel-build.md).
#
# The generated image is STRUCTURE-validated here, but is UNTESTED on real Amix
# (🟡) — verify in an emulator before trusting it.
#
# Usage:
#   tools/build-custom-bootdisk.sh --payload <dir> --out <image.adf> \
#        [--install <relpath-in-payload>] [--size 901120]
#
# The payload dir's contents are archived with paths RELATIVE to the dir, so on
# Amix they extract under "/". Put your installer at e.g. var/addon/install and
# pass --install var/addon/install.
#
# Requires: cpio (newc) OR bsdtar; dd; printf.

set -u

payload="" ; out="" ; install_rel="var/addon/install" ; size=901120
while [ $# -gt 0 ]; do
  case "$1" in
    --payload) payload="$2"; shift 2;;
    --out)     out="$2";     shift 2;;
    --install) install_rel="$2"; shift 2;;
    --size)    size="$2";    shift 2;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done
if [ -z "$payload" ] || [ -z "$out" ] || [ ! -d "$payload" ]; then
  echo "usage: $0 --payload <dir> --out <image.adf> [--install <relpath>] [--size 901120]" >&2
  exit 2
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# --- 1. the <=1 KB /sbin/sh bootstrap header (modeled on the real patch disk) ---
hdr="$tmp/header.sh"
cat > "$hdr" <<EOF
#!/sbin/sh
# THIS FILE 1024 CHARACTERS MAX
# Amix add-on disk generated by build-custom-bootdisk.sh
echo "Amix add-on disk. Extracting..."
if [ "\`/usr/bin/id\`" != "uid=0(root) gid=0(root)" ]; then
	echo "Run as root."; exit
fi
# Skip this 1 KB header, extract the trailing cpio archive into /
dd if="\$0" bs=1k iseek=1 2>/dev/null | (cd /; cpio -icdmuv)
if [ -x /$install_rel ]; then exec /$install_rel; fi
echo "Extracted. (no installer at /$install_rel)"
exit # REQUIRED
EOF

hbytes=$(wc -c <"$hdr" | tr -d ' ')
if [ "$hbytes" -gt 1024 ]; then
  echo "error: header is $hbytes bytes (>1024). Shorten it." >&2; exit 4
fi

# --- 2. build the newc cpio archive of the payload ---
cpio_ar="$tmp/payload.cpio"
( cd "$payload" || exit 5
  if command -v cpio >/dev/null 2>&1; then
    find . -print | sed 's#^\./##' | grep -v '^\.$' | cpio -o -H newc 2>/dev/null
  elif command -v bsdtar >/dev/null 2>&1; then
    bsdtar -cf - --format newc . 2>/dev/null
  else
    echo "error: need cpio or bsdtar to build the archive" >&2; exit 6
  fi
) > "$cpio_ar"
[ -s "$cpio_ar" ] || { echo "error: empty cpio archive (is --payload populated?)" >&2; exit 6; }

# --- 3. assemble: header padded to exactly 1 KB, then cpio, then zero-pad to size ---
: > "$out"
dd if="$hdr"     of="$out" bs=1024 conv=sync 2>/dev/null     # header -> first 1 KiB block, zero-padded
cat "$cpio_ar" >> "$out"
cur=$(wc -c <"$out" | tr -d ' ')
if [ "$cur" -gt "$size" ]; then
  echo "error: payload too large: $cur > $size bytes (880K floppy)." >&2; exit 7
fi
# pad to target size
dd if=/dev/zero bs=1 count=$((size - cur)) >> "$out" 2>/dev/null

# --- 4. structural self-test ---
echo "== built $out ($(wc -c <"$out" | tr -d ' ') bytes) =="
echo "-- header (first lines) --"
dd if="$out" bs=1k count=1 2>/dev/null | strings | sed 's/^/    /' | head -8
echo "-- cpio members (validated via dd skip=1 | cpio -it) --"
if command -v cpio >/dev/null 2>&1; then
  dd if="$out" bs=1k skip=1 2>/dev/null | cpio -it 2>/dev/null | sed 's/^/    /' | head -40
else
  echo "    (install cpio to list members)"
fi
echo
echo "🟡 STRUCTURE OK. This image is UNTESTED on real Amix — verify in WinUAE/FS-UAE."
echo "   See docs/boot-disks/build-pipeline.md and adding-drivers-to-boot-disk.md."
