#!/usr/bin/env bash
#
# gen-llms-full.sh — concatenate all docs (in reading order) into llms-full.txt
# at the repo root, so an LLM can ingest the whole corpus in one file.
#
# Run from anywhere; paths are resolved relative to the repo root.
# Usage: tools/gen-llms-full.sh

set -u
here="$(cd "$(dirname "$0")/.." && pwd)"   # repo root
out="$here/llms-full.txt"

# Canonical reading order (keep in sync with docs/index.md and llms.txt).
order=(
  docs/how-it-works/overview.md
  docs/how-it-works/hardware.md
  docs/how-it-works/boot-process.md
  docs/how-it-works/kernel-architecture.md
  docs/how-it-works/filesystems-and-disks.md
  docs/how-it-works/networking.md
  docs/how-it-works/x11-and-desktop.md
  docs/how-it-works/package-management.md
  docs/how-it-works/quirks.md
  docs/how-it-works/emulation-fidelity.md
  docs/how-it-works/glossary.md
  docs/getting-started/emulation-winuae.md
  docs/getting-started/emulation-fs-uae.md
  docs/getting-started/emulation-amiberry.md
  docs/getting-started/networking-on-the-lan.md
  docs/getting-started/install-walkthrough.md
  docs/getting-started/real-hardware.md
  docs/getting-started/first-login-and-tour.md
  docs/drivers/driver-model.md
  docs/drivers/kernel-build.md
  docs/drivers/writing-a-char-driver.md
  docs/drivers/writing-a-streams-driver.md
  docs/drivers/zorro-autoconfig.md
  docs/drivers/x11-rtg-drivers.md
  docs/drivers/toolchain.md
  docs/drivers/case-studies/va2000.md
  docs/drivers/case-studies/xrtg.md
  docs/drivers/case-studies/lszorro.md
  docs/drivers/case-studies/hydra.md
  docs/drivers/case-studies/zz9000.md
  docs/drivers/case-studies/x11r63-zz9000.md
  docs/drivers/case-studies/mesa31.md
  docs/drivers/a4091-53c710-driver.md
  docs/drivers/z3660-ethernet-driver.md
  docs/drivers/z3660-scsi-driver.md
  docs/boot-disks/anatomy-boot-adf.md
  docs/boot-disks/anatomy-root-adf.md
  docs/boot-disks/anatomy-patch-adf.md
  docs/boot-disks/reverse-engineering-boot-adf.md
  docs/boot-disks/adding-drivers-to-boot-disk.md
  docs/boot-disks/build-pipeline.md
  docs/reference/versions.md
  docs/reference/device-list.md
  docs/reference/commands-cheatsheet.md
  docs/reference/bibliography.md
  docs/contributing/style-guide.md
  docs/contributing/writing-for-llms.md
)

{
  echo "# grimoire-amix — full corpus (llms-full.txt)"
  echo
  echo "> Documentation for Amiga Unix (Amix), Commodore's port of AT&T System V Release 4"
  echo "> to 68030 Amigas. Generated by tools/gen-llms-full.sh — do not edit by hand."
  echo "> Source of truth and citations: sources/research-brief.md."
  echo
} > "$out"

missing=0
for f in "${order[@]}"; do
  if [ -f "$here/$f" ]; then
    {
      echo
      echo "================================================================================"
      echo "# FILE: $f"
      echo "================================================================================"
      echo
      cat "$here/$f"
      echo
    } >> "$out"
  else
    echo "warning: missing $f (skipped)" >&2
    missing=$((missing + 1))
  fi
done

bytes=$(wc -c <"$out" | tr -d ' ')
echo "wrote $out ($bytes bytes, ${#order[@]} pages, $missing missing)"
